services:
  - type: web
    name: netflix-portfolio
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npx serve -s build -l 3000
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: CI
        value: false
    headers:
      - path: /
        name: Strict-Transport-Security
        value: max-age=31536000; includeSubDomains
